'use strict';
const ACTION_TEXT={
 de:{resetTitle:'Neues Passwort festlegen',resetSubtitle:'Lege ein neues Passwort für dein Doori-Konto fest.',password:'Neues Passwort',confirm:'Passwort wiederholen',save:'Passwort speichern',checking:'Der Link wird geprüft…',saving:'Passwort wird gespeichert…',resetSuccess:'Dein Passwort wurde geändert. Du kannst dich jetzt anmelden.',verifyTitle:'E-Mail-Adresse bestätigen',verifySubtitle:'Deine E-Mail-Adresse wird sicher bestätigt.',verifying:'E-Mail-Adresse wird bestätigt…',verifySuccess:'Deine E-Mail-Adresse wurde bestätigt. Du kannst dich jetzt anmelden.',invalid:'Dieser Link ist ungültig oder abgelaufen. Fordere bitte einen neuen Link im Messenger an.',mismatch:'Die beiden Passwörter stimmen nicht überein.',weak:'Das Passwort muss mindestens 6 Zeichen lang sein.',back:'Zurück zum Messenger'},
 en:{resetTitle:'Set a new password',resetSubtitle:'Set a new password for your Doori account.',password:'New password',confirm:'Repeat password',save:'Save password',checking:'Checking the link…',saving:'Saving your password…',resetSuccess:'Your password has been changed. You can now sign in.',verifyTitle:'Verify email address',verifySubtitle:'Your email address is being securely verified.',verifying:'Verifying your email address…',verifySuccess:'Your email address has been verified. You can now sign in.',invalid:'This link is invalid or has expired. Please request a new link in the messenger.',mismatch:'The two passwords do not match.',weak:'The password must contain at least 6 characters.',back:'Back to Messenger'},
 ar:{resetTitle:'تعيين كلمة مرور جديدة',resetSubtitle:'عيّن كلمة مرور جديدة لحسابك في Doori.',password:'كلمة المرور الجديدة',confirm:'تكرار كلمة المرور',save:'حفظ كلمة المرور',checking:'جارٍ التحقق من الرابط…',saving:'جارٍ حفظ كلمة المرور…',resetSuccess:'تم تغيير كلمة المرور. يمكنك الآن تسجيل الدخول.',verifyTitle:'تأكيد البريد الإلكتروني',verifySubtitle:'جارٍ تأكيد بريدك الإلكتروني بأمان.',verifying:'جارٍ تأكيد البريد الإلكتروني…',verifySuccess:'تم تأكيد بريدك الإلكتروني. يمكنك الآن تسجيل الدخول.',invalid:'هذا الرابط غير صالح أو انتهت صلاحيته. اطلب رابطاً جديداً من برنامج المراسلة.',mismatch:'كلمتا المرور غير متطابقتين.',weak:'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',back:'العودة إلى المراسلة'},
 fa:{resetTitle:'تعیین گذرواژه جدید',resetSubtitle:'برای حساب Doori خود گذرواژه جدیدی تعیین کنید.',password:'گذرواژه جدید',confirm:'تکرار گذرواژه',save:'ذخیره گذرواژه',checking:'در حال بررسی پیوند…',saving:'در حال ذخیره گذرواژه…',resetSuccess:'گذرواژه شما تغییر کرد. اکنون می‌توانید وارد شوید.',verifyTitle:'تأیید ایمیل',verifySubtitle:'ایمیل شما به‌صورت امن تأیید می‌شود.',verifying:'در حال تأیید ایمیل…',verifySuccess:'ایمیل شما تأیید شد. اکنون می‌توانید وارد شوید.',invalid:'این پیوند نامعتبر است یا منقضی شده است. لطفاً در پیام‌رسان پیوند جدیدی درخواست کنید.',mismatch:'دو گذرواژه یکسان نیستند.',weak:'گذرواژه باید حداقل ۶ نویسه داشته باشد.',back:'بازگشت به پیام‌رسان'},
 tr:{resetTitle:'Yeni şifre belirle',resetSubtitle:'Doori hesabınız için yeni bir şifre belirleyin.',password:'Yeni şifre',confirm:'Şifreyi tekrarla',save:'Şifreyi kaydet',checking:'Bağlantı kontrol ediliyor…',saving:'Şifreniz kaydediliyor…',resetSuccess:'Şifreniz değiştirildi. Şimdi giriş yapabilirsiniz.',verifyTitle:'E-posta adresini doğrula',verifySubtitle:'E-posta adresiniz güvenli şekilde doğrulanıyor.',verifying:'E-posta adresiniz doğrulanıyor…',verifySuccess:'E-posta adresiniz doğrulandı. Şimdi giriş yapabilirsiniz.',invalid:'Bu bağlantı geçersiz veya süresi dolmuş. Lütfen Messenger üzerinden yeni bir bağlantı isteyin.',mismatch:'İki şifre eşleşmiyor.',weak:'Şifre en az 6 karakter içermelidir.',back:'Messenger’a dön'}
};
const params=new URLSearchParams(location.search),language=ACTION_TEXT[params.get('lang')]?params.get('lang'):'en',text=ACTION_TEXT[language];
document.documentElement.lang=language;document.documentElement.dir=language==='ar'||language==='fa'?'rtl':'ltr';
const title=document.getElementById('title'),subtitle=document.getElementById('subtitle'),status=document.getElementById('status'),form=document.getElementById('reset-form'),back=document.getElementById('back-link'),submit=document.getElementById('submit-button');
document.getElementById('password-label').textContent=text.password;document.getElementById('confirm-label').textContent=text.confirm;submit.textContent=text.save;back.textContent=text.back;
firebase.initializeApp({apiKey:'AIzaSyAIV8HtZGe8RBzqcDLwc8RT2iY3TSWrnIk',authDomain:'doori-messenger.firebaseapp.com',projectId:'doori-messenger'});const auth=firebase.auth(),code=params.get('oobCode'),mode=params.get('mode');
function message(value,type=''){status.textContent=value;status.className='status'+(type?' '+type:'');}
function finish(value){message(value,'success');form.classList.add('hidden');back.classList.remove('hidden');history.replaceState({},'',`/account/action?lang=${encodeURIComponent(language)}`);}
function fail(){title.textContent='Doori Messenger';subtitle.textContent='';message(text.invalid,'error');form.classList.add('hidden');back.classList.remove('hidden');}
if(!code)fail();
else if(mode==='resetPassword'){
 title.textContent=text.resetTitle;subtitle.textContent=text.resetSubtitle;message(text.checking);
 auth.verifyPasswordResetCode(code).then(()=>{status.classList.add('hidden');form.classList.remove('hidden');}).catch(fail);
 form.addEventListener('submit',async event=>{event.preventDefault();const password=document.getElementById('password').value,confirm=document.getElementById('confirm-password').value;if(password.length<6){message(text.weak,'error');return;}if(password!==confirm){message(text.mismatch,'error');return;}submit.disabled=true;message(text.saving);status.classList.remove('hidden');try{await auth.confirmPasswordReset(code,password);finish(text.resetSuccess);}catch{fail();}finally{submit.disabled=false;}});
}else if(mode==='verifyEmail'){
 title.textContent=text.verifyTitle;subtitle.textContent=text.verifySubtitle;message(text.verifying);auth.applyActionCode(code).then(()=>finish(text.verifySuccess)).catch(fail);
}else fail();
