'use strict';
const ACTION_TEXT={
 de:{resetTitle:'Neues Passwort festlegen',resetSubtitle:'Lege ein neues Passwort für dein Doori-Konto fest.',password:'Neues Passwort',confirm:'Passwort wiederholen',save:'Passwort speichern',checking:'Der Link wird geprüft…',saving:'Passwort wird gespeichert…',resetSuccess:'Dein Passwort wurde geändert. Du kannst dich jetzt anmelden.',verifyTitle:'E-Mail-Adresse bestätigen',verifySubtitle:'Deine E-Mail-Adresse wird sicher bestätigt.',verifying:'E-Mail-Adresse wird bestätigt…',verifySuccess:'Deine E-Mail-Adresse wurde bestätigt. Du kannst dich jetzt anmelden.',invalid:'Dieser Link ist ungültig oder abgelaufen. Fordere bitte einen neuen Link im Messenger an.',mismatch:'Die beiden Passwörter stimmen nicht überein.',weak:'Das Passwort muss mindestens 6 Zeichen lang sein.',back:'Zurück zum Messenger',deleteTitle:'Konto endgültig löschen',deleteSubtitle:'Bestätige die endgültige Löschung deines Kontos.',deleteWarning:'Achtung: Diese Aktion kann nicht rückgängig gemacht werden. Alle Nachrichten, Medien, Kontakte und Daten werden unwiderruflich gelöscht.',deleteButton:'Konto jetzt endgültig löschen',deleting:'Konto wird gelöscht…',deleteSuccess:'Dein Konto wurde erfolgreich gelöscht. Eine Bestätigungs-E-Mail wurde an dich gesendet.'},
 en:{resetTitle:'Set a new password',resetSubtitle:'Set a new password for your Doori account.',password:'New password',confirm:'Repeat password',save:'Save password',checking:'Checking the link…',saving:'Saving your password…',resetSuccess:'Your password has been changed. You can now sign in.',verifyTitle:'Verify email address',verifySubtitle:'Your email address is being securely verified.',verifying:'Verifying your email address…',verifySuccess:'Your email address has been verified. You can now sign in.',invalid:'This link is invalid or has expired. Please request a new link in the messenger.',mismatch:'The two passwords do not match.',weak:'The password must contain at least 6 characters.',back:'Back to Messenger',deleteTitle:'Delete account permanently',deleteSubtitle:'Confirm the permanent deletion of your account.',deleteWarning:'Warning: This action cannot be undone. All messages, media, contacts, and data will be permanently deleted.',deleteButton:'Permanently delete account now',deleting:'Deleting account…',deleteSuccess:'Your account has been successfully deleted. A confirmation email has been sent to you.'},
 ar:{resetTitle:'تعيين كلمة مرور جديدة',resetSubtitle:'عيّن كلمة مرور جديدة لحسابك في Doori.',password:'كلمة المرور الجديدة',confirm:'تكرار كلمة المرور',save:'حفظ كلمة المرور',checking:'جارٍ التحقق من الرابط…',saving:'جارٍ حفظ كلمة المرور…',resetSuccess:'تم تغيير كلمة المرور. يمكنك الآن تسجيل الدخول.',verifyTitle:'تأكيد البريد الإلكتروني',verifySubtitle:'جارٍ تأكيد بريدك الإلكتروني بأمان.',verifying:'جارٍ تأكيد البريد الإلكتروني…',verifySuccess:'تم تأكيد بريدك الإلكتروني. يمكنك الآن تسجيل الدخول.',invalid:'هذا الرابط غير صالح أو انتهت صلاحيته. اطلب رابطاً جديداً من برنامج المراسلة.',mismatch:'كلمتا المرور غير متطابقتين.',weak:'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',back:'العودة إلى المراسلة',deleteTitle:'حذف الحساب نهائياً',deleteSubtitle:'تأكيد حذف حسابك بشكل نهائي.',deleteWarning:'تحذير: لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع الرسائل والوسائط وجهات الاتصال والبيانات نهائياً.',deleteButton:'حذف الحساب نهائياً الآن',deleting:'جارٍ حذف الحساب…',deleteSuccess:'تم حذف حسابك بنجاح. تم إرسال رسالة تأكيد إلى بريدك الإلكتروني.'},
 fa:{resetTitle:'تعیین گذرواژه جدید',resetSubtitle:'برای حساب Doori خود گذرواژه جدیدی تعیین کنید.',password:'گذرواژه جدید',confirm:'تکرار گذرواژه',save:'ذخیره گذرواژه',checking:'در حال بررسی پیوند…',saving:'در حال ذخیره گذرواژه…',resetSuccess:'گذرواژه شما تغییر کرد. اکنون می‌توانید وارد شوید.',verifyTitle:'تأیید ایمیل',verifySubtitle:'ایمیل شما به‌صورت امن تأیید می‌شود.',verifying:'در حال تأیید ایمیل…',verifySuccess:'ایمیل شما تأیید شد. اکنون می‌توانید وارد شوید.',invalid:'این پیوند نامعتبر است یا منقضی شده است. لطفاً در پیام‌رسان پیوند جدیدی درخواست کنید.',mismatch:'دو گذرواژه یکسان نیستند.',weak:'گذرواژه باید حداقل ۶ نویسه داشته باشد.',back:'بازگشت به پیام‌رسان',deleteTitle:'حذف دائمی حساب کاربری',deleteSubtitle:'تأیید حذف دائمی حساب کاربری شما.',deleteWarning:'هشدار: این اقدام غیرقابل بازگشت است. همه پیام‌ها، رسانه‌ها، مخاطبین و داده‌ها برای همیشه حذف خواهند شد.',deleteButton:'اکنون حساب برای همیشه حذف شود',deleting:'در حال حذف حساب…',deleteSuccess:'حساب شما با موفقیت حذف شد. یک ایمیل تأیید برای شما ارسال گردید.'},
 tr:{resetTitle:'Yeni şifre belirle',resetSubtitle:'Doori hesabınız için yeni bir şifre belirleyin.',password:'Yeni şifre',confirm:'Şifreyi tekrarla',save:'Şifreyi kaydet',checking:'Bağlantı kontrol ediliyor…',saving:'Şifreniz kaydediliyor…',resetSuccess:'Şifreniz değiştirildi. Şimdi giriş yapabilirsiniz.',verifyTitle:'E-posta adresini doğrula',verifySubtitle:'E-posta adresiniz güvenli şekilde doğrulanıyor.',verifying:'E-posta adresiniz doğrulanıyor…',verifySuccess:'E-posta adresiniz doğrulandı. Şimdi giriş yapabilirsiniz.',invalid:'Bu bağlantı geçersiz veya süresi dolmuş. Lütfen Messenger üzerinden yeni bir bağlantı isteyin.',mismatch:'İki şifre eşleşmiyor.',weak:'Şifre en az 6 karakter içermelidir.',back:'Messenger’a dön',deleteTitle:'Hesabı kalıcı olarak sil',deleteSubtitle:'Hesabınızın kalıcı olarak silinmesini onaylayın.',deleteWarning:'Uyarı: Bu işlem geri alınamaz. Tüm mesajlar, medyalar, kişiler ve veriler kalıcı olarak silinecektir.',deleteButton:'Hesabı şimdi kalıcı olarak sil',deleting:'Hesap siliniyor…',deleteSuccess:'Hesabınız başarıyla silindi. Tarafınıza bir onay e-postası gönderildi.'}
};
const params=new URLSearchParams(location.search),language=ACTION_TEXT[params.get('lang')]?params.get('lang'):'en',text=ACTION_TEXT[language];
document.documentElement.lang=language;document.documentElement.dir=language==='ar'||language==='fa'?'rtl':'ltr';
const title=document.getElementById('title'),subtitle=document.getElementById('subtitle'),status=document.getElementById('status'),form=document.getElementById('reset-form'),deleteBox=document.getElementById('delete-box'),deleteWarning=document.getElementById('delete-warning'),deleteConfirmBtn=document.getElementById('delete-confirm-button'),back=document.getElementById('back-link'),submit=document.getElementById('submit-button');
if(document.getElementById('password-label'))document.getElementById('password-label').textContent=text.password;
if(document.getElementById('confirm-label'))document.getElementById('confirm-label').textContent=text.confirm;
if(submit)submit.textContent=text.save;
if(back)back.textContent=text.back;
firebase.initializeApp({apiKey:'AIzaSyAIV8HtZGe8RBzqcDLwc8RT2iY3TSWrnIk',authDomain:'doori-messenger.firebaseapp.com',projectId:'doori-messenger'});const auth=firebase.auth(),code=params.get('oobCode'),mode=params.get('mode'),token=params.get('token');
function message(value,type=''){status.textContent=value;status.className='status'+(type?' '+type:'');}
function finish(value){message(value,'success');if(form)form.classList.add('hidden');if(deleteBox)deleteBox.classList.add('hidden');if(back)back.classList.remove('hidden');history.replaceState({},'',`/account/action?lang=${encodeURIComponent(language)}`);}
function fail(){title.textContent='Doori Messenger';subtitle.textContent='';message(text.invalid,'error');if(form)form.classList.add('hidden');if(deleteBox)deleteBox.classList.add('hidden');if(back)back.classList.remove('hidden');}

if(mode==='deleteAccount'){
 if(!token||!/^[a-f0-9]{64}$/.test(token))fail();
 else{
  title.textContent=text.deleteTitle;subtitle.textContent=text.deleteSubtitle;
  if(deleteWarning)deleteWarning.textContent=text.deleteWarning;
  if(deleteConfirmBtn)deleteConfirmBtn.textContent=text.deleteButton;
  if(deleteBox)deleteBox.classList.remove('hidden');
  if(deleteConfirmBtn)deleteConfirmBtn.addEventListener('click',async()=>{
   deleteConfirmBtn.disabled=true;message(text.deleting);status.classList.remove('hidden');
   try{
    const confirmFn=firebase.app().functions('europe-west3').httpsCallable('confirmAccountDeletion');
    await confirmFn({token,language});
    finish(text.deleteSuccess);
   }catch(err){console.error('Delete account confirmation error',err);fail();}
  });
 }
}else if(!code)fail();
else if(mode==='resetPassword'){
 title.textContent=text.resetTitle;subtitle.textContent=text.resetSubtitle;message(text.checking);
 auth.verifyPasswordResetCode(code).then(()=>{status.classList.add('hidden');form.classList.remove('hidden');}).catch(fail);
 form.addEventListener('submit',async event=>{event.preventDefault();const password=document.getElementById('password').value,confirm=document.getElementById('confirm-password').value;if(password.length<6){message(text.weak,'error');return;}if(password!==confirm){message(text.mismatch,'error');return;}submit.disabled=true;message(text.saving);status.classList.remove('hidden');try{await auth.confirmPasswordReset(code,password);finish(text.resetSuccess);}catch{fail();}finally{submit.disabled=false;}});
}else if(mode==='verifyEmail'){
 title.textContent=text.verifyTitle;subtitle.textContent=text.verifySubtitle;message(text.verifying);auth.applyActionCode(code).then(()=>finish(text.verifySuccess)).catch(fail);
}else fail();
