(function () {
  'use strict';
  const I18N = {
    de:{games_menu:'Spiele',hub:'Gemeinsam spielen',sub:'Wähle ein Spiel für diesen privaten Chat.',classic:'Klassiker-Duell',classicDesc:'Tic-Tac-Toe oder Vier gewinnt',ttt:'Tic-Tac-Toe',c4:'Vier gewinnt',memory:'Memory-Duell',memoryDesc:'Finde mehr Paare als dein Gegner.',quiz:'Quiz-Duell',quizDesc:'Wissen, Tempo und Punkte.',battle:'Schiffe versenken',battleDesc:'Finde und versenke die gegnerische Flotte.',start:'Spiel starten',close:'Schließen',waiting:'Warte auf den Mitspieler …',yourTurn:'Du bist am Zug',theirTurn:'Der Mitspieler ist am Zug',youWin:'Du hast gewonnen!',youLose:'Der Mitspieler hat gewonnen.',draw:'Unentschieden',rematch:'Revanche',open:'Spiel öffnen',invite:'hat dich zu einem Spiel eingeladen',dmOnly:'Spiele sind nur in privaten Chats verfügbar.',pairs:'Paare',score:'Punkte',ships:'Schiffe',hit:'Treffer!',miss:'Daneben',quizDone:'Quiz beendet'},
    en:{games_menu:'Games',hub:'Play together',sub:'Choose a game for this private chat.',classic:'Classic Duel',classicDesc:'Tic-Tac-Toe or Connect Four',ttt:'Tic-Tac-Toe',c4:'Connect Four',memory:'Memory Duel',memoryDesc:'Find more pairs than your opponent.',quiz:'Quiz Duel',quizDesc:'Knowledge, speed and points.',battle:'Battleship',battleDesc:'Find and sink the opposing fleet.',start:'Start game',close:'Close',waiting:'Waiting for the other player …',yourTurn:'Your turn',theirTurn:"Other player's turn",youWin:'You won!',youLose:'The other player won.',draw:'Draw',rematch:'Rematch',open:'Open game',invite:'invited you to a game',dmOnly:'Games are only available in private chats.',pairs:'Pairs',score:'Points',ships:'Ships',hit:'Hit!',miss:'Miss',quizDone:'Quiz finished'},
    ar:{games_menu:'الألعاب',hub:'العبا معًا',sub:'اختر لعبة لهذه الدردشة الخاصة.',classic:'مواجهة كلاسيكية',classicDesc:'إكس-أو أو أربعة على التوالي',ttt:'إكس-أو',c4:'أربعة على التوالي',memory:'تحدي الذاكرة',memoryDesc:'اعثر على أزواج أكثر من منافسك.',quiz:'تحدي المعلومات',quizDesc:'معرفة وسرعة ونقاط.',battle:'معركة السفن',battleDesc:'اعثر على أسطول الخصم وأغرقه.',start:'ابدأ اللعبة',close:'إغلاق',waiting:'في انتظار اللاعب الآخر …',yourTurn:'دورك',theirTurn:'دور اللاعب الآخر',youWin:'لقد فزت!',youLose:'فاز اللاعب الآخر.',draw:'تعادل',rematch:'إعادة اللعب',open:'فتح اللعبة',invite:'دعاك إلى لعبة',dmOnly:'الألعاب متاحة فقط في الدردشات الخاصة.',pairs:'الأزواج',score:'النقاط',ships:'السفن',hit:'إصابة!',miss:'لم تصب',quizDone:'انتهى الاختبار'},
    fa:{games_menu:'بازی‌ها',hub:'با هم بازی کنید',sub:'برای این گفت‌وگوی خصوصی یک بازی انتخاب کنید.',classic:'رقابت کلاسیک',classicDesc:'دوز یا چهار در یک ردیف',ttt:'دوز',c4:'چهار در یک ردیف',memory:'رقابت حافظه',memoryDesc:'جفت‌های بیشتری از حریف پیدا کنید.',quiz:'مسابقه دانستنی‌ها',quizDesc:'دانش، سرعت و امتیاز.',battle:'نبرد کشتی‌ها',battleDesc:'ناوگان حریف را پیدا و غرق کنید.',start:'شروع بازی',close:'بستن',waiting:'در انتظار بازیکن دیگر …',yourTurn:'نوبت شماست',theirTurn:'نوبت بازیکن دیگر است',youWin:'شما برنده شدید!',youLose:'بازیکن دیگر برنده شد.',draw:'مساوی',rematch:'بازی دوباره',open:'باز کردن بازی',invite:'شما را به یک بازی دعوت کرد',dmOnly:'بازی‌ها فقط در گفت‌وگوهای خصوصی در دسترس‌اند.',pairs:'جفت‌ها',score:'امتیاز',ships:'کشتی‌ها',hit:'اصابت!',miss:'خطا',quizDone:'مسابقه تمام شد'},
    tr:{games_menu:'Oyunlar',hub:'Birlikte oynayın',sub:'Bu özel sohbet için bir oyun seçin.',classic:'Klasik Düello',classicDesc:'XOX veya Dört Bir Arada',ttt:'XOX',c4:'Dört Bir Arada',memory:'Hafıza Düellosu',memoryDesc:'Rakibinden daha fazla çift bul.',quiz:'Bilgi Düellosu',quizDesc:'Bilgi, hız ve puan.',battle:'Amiral Battı',battleDesc:'Rakibin filosunu bul ve batır.',start:'Oyunu başlat',close:'Kapat',waiting:'Diğer oyuncu bekleniyor …',yourTurn:'Sıra sende',theirTurn:'Sıra diğer oyuncuda',youWin:'Kazandın!',youLose:'Diğer oyuncu kazandı.',draw:'Berabere',rematch:'Rövanş',open:'Oyunu aç',invite:'seni bir oyuna davet etti',dmOnly:'Oyunlar yalnızca özel sohbetlerde kullanılabilir.',pairs:'Çiftler',score:'Puan',ships:'Gemiler',hit:'İsabet!',miss:'Iska',quizDone:'Bilgi yarışması bitti'}
  };
  const QUESTIONS={
    de:[['Welcher Planet ist der Sonne am nächsten?',['Merkur','Venus','Mars','Erde'],0],['Wie viele Kontinente gibt es?',['5','6','7','8'],2],['Welche Farbe entsteht aus Blau und Gelb?',['Grün','Lila','Orange','Rot'],0],['Wie viele Minuten hat eine Stunde?',['30','45','60','90'],2],['Was ist die Hauptstadt der Türkei?',['Istanbul','Ankara','Izmir','Bursa'],1],['Welches Tier ist das größte?',['Elefant','Blauwal','Giraffe','Hai'],1]],
    en:[['Which planet is closest to the Sun?',['Mercury','Venus','Mars','Earth'],0],['How many continents are there?',['5','6','7','8'],2],['What color do blue and yellow make?',['Green','Purple','Orange','Red'],0],['How many minutes are in an hour?',['30','45','60','90'],2],['What is the capital of Türkiye?',['Istanbul','Ankara','Izmir','Bursa'],1],['Which animal is the largest?',['Elephant','Blue whale','Giraffe','Shark'],1]],
    ar:[['ما الكوكب الأقرب إلى الشمس؟',['عطارد','الزهرة','المريخ','الأرض'],0],['كم عدد القارات؟',['5','6','7','8'],2],['ما اللون الناتج عن الأزرق والأصفر؟',['الأخضر','البنفسجي','البرتقالي','الأحمر'],0],['كم دقيقة في الساعة؟',['30','45','60','90'],2],['ما عاصمة تركيا؟',['إسطنبول','أنقرة','إزمير','بورصة'],1],['ما أكبر حيوان؟',['الفيل','الحوت الأزرق','الزرافة','القرش'],1]],
    fa:[['نزدیک‌ترین سیاره به خورشید کدام است؟',['عطارد','زهره','مریخ','زمین'],0],['چند قاره وجود دارد؟',['5','6','7','8'],2],['ترکیب آبی و زرد چه رنگی می‌شود؟',['سبز','بنفش','نارنجی','قرمز'],0],['یک ساعت چند دقیقه است؟',['30','45','60','90'],2],['پایتخت ترکیه چیست؟',['استانبول','آنکارا','ازمیر','بورسا'],1],['بزرگ‌ترین حیوان کدام است؟',['فیل','نهنگ آبی','زرافه','کوسه'],1]],
    tr:[['Güneşe en yakın gezegen hangisidir?',['Merkür','Venüs','Mars','Dünya'],0],['Kaç kıta vardır?',['5','6','7','8'],2],['Mavi ve sarı karışınca hangi renk olur?',['Yeşil','Mor','Turuncu','Kırmızı'],0],['Bir saat kaç dakikadır?',['30','45','60','90'],2],['Türkiye’nin başkenti neresidir?',['İstanbul','Ankara','İzmir','Bursa'],1],['En büyük hayvan hangisidir?',['Fil','Mavi balina','Zürafa','Köpek balığı'],1]]
  };
  let modal,body,unsub,current=null;
  const lang=()=>window.currentLang||'en', t=()=>I18N[lang()]||I18N.en, me=()=>String(window.currentUser||'').toLowerCase();
  const esc=s=>window.escapeHTML?window.escapeHTML(String(s)):String(s);
  const nameOf=type=>({tictactoe:t().ttt,connect4:t().c4,memory:t().memory,quiz:t().quiz,battleship:t().battle}[type]||type);
  const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
  function ensureModal(){if(modal)return;modal=document.createElement('div');modal.id='games-modal';modal.className='modal hidden';modal.innerHTML='<div class="games-shell glass-panel"><button class="games-close" aria-label="Close">×</button><div id="games-body"></div></div>';document.body.appendChild(modal);body=modal.querySelector('#games-body');modal.querySelector('.games-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close();};}
  function close(){unsub?.();unsub=null;current=null;modal?.classList.add('hidden');}
  function card(icon,title,desc,buttons){return `<article class="game-card"><div class="game-icon">${icon}</div><h3>${esc(title)}</h3><p>${esc(desc)}</p><div class="game-card-actions">${buttons}</div></article>`;}
  function openHub(){ensureModal();const chat=window.currentChat;if(!chat||chat.type!=='dm'){alert(t().dmOnly);return;}modal.classList.remove('hidden');body.innerHTML=`<header class="games-head"><span>🎮</span><div><h2>${esc(t().hub)}</h2><p>${esc(t().sub)}</p></div></header><div class="games-grid">${card('⭕',t().classic,t().classicDesc,`<button data-new-game="tictactoe">${esc(t().ttt)}</button><button data-new-game="connect4">${esc(t().c4)}</button>`)}${card('🧠',t().memory,t().memoryDesc,`<button data-new-game="memory">${esc(t().start)}</button>`)}${card('✨',t().quiz,t().quizDesc,`<button data-new-game="quiz">${esc(t().start)}</button>`)}${card('🚢',t().battle,t().battleDesc,`<button data-new-game="battleship">${esc(t().start)}</button>`)}</div><div id="active-games"></div>`;body.querySelectorAll('[data-new-game]').forEach(b=>b.onclick=()=>create(b.dataset.newGame));loadActive();}
  function initial(type,players){if(type==='tictactoe')return{board:Array(9).fill(''),turn:0,winner:null};if(type==='connect4')return{board:Array(42).fill(''),turn:0,winner:null};if(type==='memory')return{deck:shuffle(['🌙','🌙','⭐','⭐','🌈','🌈','🍀','🍀','🎈','🎈','🦋','🦋','🍉','🍉','🚀','🚀']),open:[],matched:[],scores:[0,0],turn:0,winner:null};if(type==='quiz')return{order:shuffle([0,1,2,3,4,5]),index:0,scores:[0,0],turn:0,winner:null};return{boards:[fleet(),fleet()],shots:[{},{}],hits:[0,0],turn:0,winner:null};}
  function fleet(){const board=Array(100).fill(0),sizes=[5,4,3,3,2];for(const size of sizes){let ok=false;while(!ok){const h=Math.random()<.5,r=Math.floor(Math.random()*(h?10:11-size)),c=Math.floor(Math.random()*(h?11-size:10)),cells=Array.from({length:size},(_,i)=>(r+(h?0:i))*10+c+(h?i:0));if(cells.every(x=>!board[x])){cells.forEach(x=>board[x]=1);ok=true;}}}return board;}
  async function create(type){const opponent=String(window.currentChat.id).toLowerCase(),players=[me(),opponent];const ref=window.db.collection('gameSessions').doc();await ref.set({type,participants:players,createdBy:me(),status:'active',round:1,state:initial(type,players),createdAt:Date.now(),updatedAt:Date.now()});window.sendMessage('', 'game_invite', JSON.stringify({id:ref.id,type}));open(ref.id);}
  async function loadActive(){const box=body.querySelector('#active-games');try{const q=await window.db.collection('gameSessions').where('participants','array-contains',me()).limit(12).get();const docs=q.docs.filter(d=>d.data().status!=='finished').slice(0,5);if(docs.length)box.innerHTML='<div class="active-games">'+docs.map(d=>`<button data-open-game="${d.id}">▶ ${esc(nameOf(d.data().type))}</button>`).join('')+'</div>';box?.querySelectorAll('[data-open-game]').forEach(b=>b.onclick=()=>open(b.dataset.openGame));}catch(e){console.error(e);}}
  function open(id){ensureModal();modal.classList.remove('hidden');unsub?.();unsub=window.db.collection('gameSessions').doc(id).onSnapshot(s=>{if(!s.exists)return close();current={id,...s.data()};render();},e=>{console.error(e);close();});}
  window.openDooriGame=open;
  window.renderDooriGameInvite=msg=>{try{const x=JSON.parse(msg.mediaUrl||'{}');return `<div class="game-invite"><span>🎮</span><b>${esc(nameOf(x.type))}</b><small>${esc(msg.sender_username)} ${esc(t().invite)}</small><button data-doori-action="openDooriGame" data-doori-args="${esc(JSON.stringify([x.id]))}">${esc(t().open)}</button></div>`;}catch{return '';}};
  async function transact(mutator){const ref=window.db.collection('gameSessions').doc(current.id);await window.db.runTransaction(async tx=>{const snap=await tx.get(ref),d=snap.data();if(!d)return;const next=mutator(structuredClone(d.state),d);if(next)tx.update(ref,{state:next,stateVersion:(d.stateVersion||0)+1,updatedAt:Date.now(),status:next.winner!==null?'finished':'active'});});}
  const myIndex=()=>current.participants.indexOf(me());
  function status(s){if(s.winner!==null&&s.winner!==undefined)return s.winner==='draw'?t().draw:(s.winner===myIndex()?t().youWin:t().youLose);return s.turn===myIndex()?t().yourTurn:t().theirTurn;}
  function render(){const s=current.state,type=current.type;let game='';if(type==='tictactoe')game=grid(s.board,3,'ttt');else if(type==='connect4')game=grid(s.board,7,'c4');else if(type==='memory')game=memory(s);else if(type==='quiz')game=quiz(s);else game=battle(s);body.innerHTML=`<header class="games-head"><span>🎮</span><div><h2>${esc(nameOf(type))}</h2><p class="game-status">${esc(status(s))}</p></div></header>${game}${s.winner!==null&&s.winner!==undefined?`<button id="game-rematch" class="game-rematch">↻ ${esc(t().rematch)}</button>`:''}`;body.querySelector('#game-rematch')?.addEventListener('click',()=>transact(()=>initial(type,current.participants)));}
  function winLine(b,rows,cols,n){for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)for(const [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]){const cells=[];for(let k=0;k<n;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=rows||cc<0||cc>=cols){cells.length=0;break;}cells.push(rr*cols+cc);}if(cells.length&&b[cells[0]]&&cells.every(i=>b[i]===b[cells[0]]))return b[cells[0]];}return null;}
  function grid(board,cols,kind){setTimeout(()=>body.querySelectorAll('[data-cell]').forEach(x=>x.onclick=()=>transact(s=>{if(s.turn!==myIndex()||s.winner!==null)return;if(kind==='ttt'){const i=+x.dataset.cell;if(s.board[i])return;s.board[i]=String(myIndex()+1);const w=winLine(s.board,3,3,3);s.winner=w?+w-1:(s.board.every(Boolean)?'draw':null);}else{const col=+x.dataset.cell;let i=-1;for(let r=5;r>=0;r--)if(!s.board[r*7+col]){i=r*7+col;break;}if(i<0)return;s.board[i]=String(myIndex()+1);const w=winLine(s.board,6,7,4);s.winner=w?+w-1:(s.board.every(Boolean)?'draw':null);}s.turn=1-s.turn;return s;})),0);return `<div class="game-board ${kind}">${board.map((v,i)=>`<button data-cell="${kind==='c4'?i%7:i}" class="p${v||0}">${kind==='ttt'?(v==='1'?'×':v==='2'?'○':''):''}</button>`).join('')}</div>`;}
  function memory(s){setTimeout(()=>body.querySelectorAll('[data-card]').forEach(x=>x.onclick=()=>transact(n=>{const i=+x.dataset.card;if(n.turn!==myIndex()||n.matched.includes(i))return;if(n.open.length===2)n.open=[];if(n.open.includes(i))return;n.open.push(i);if(n.open.length===2){const [a,b]=n.open;if(n.deck[a]===n.deck[b]){n.matched.push(a,b);n.scores[n.turn]++;n.open=[];if(n.matched.length===n.deck.length)n.winner=n.scores[0]===n.scores[1]?'draw':(n.scores[0]>n.scores[1]?0:1);}else n.turn=1-n.turn;}return n;})),0);return `<div class="game-score">${esc(t().pairs)}: ${s.scores[0]} – ${s.scores[1]}</div><div class="memory-board">${s.deck.map((v,i)=>`<button data-card="${i}" class="${s.matched.includes(i)?'matched':''}">${s.open.includes(i)||s.matched.includes(i)?v:'?'}</button>`).join('')}</div>`;}
  function quiz(s){if(s.winner!==null)return `<div class="quiz-finish">🏆 ${esc(t().quizDone)}<br>${esc(t().score)}: ${s.scores[0]} – ${s.scores[1]}</div>`;const q=(QUESTIONS[lang()]||QUESTIONS.en)[s.order[s.index%6]];setTimeout(()=>body.querySelectorAll('[data-answer]').forEach(x=>x.onclick=()=>transact(n=>{if(n.turn!==myIndex()||n.winner!==null)return;const base=QUESTIONS.en[n.order[n.index%6]];if(+x.dataset.answer===base[2])n.scores[n.turn]++;n.index++;n.turn=1-n.turn;if(n.index>=12)n.winner=n.scores[0]===n.scores[1]?'draw':(n.scores[0]>n.scores[1]?0:1);return n;})),0);return `<div class="game-score">${esc(t().score)}: ${s.scores[0]} – ${s.scores[1]}</div><div class="quiz-card"><h3>${esc(q[0])}</h3>${q[1].map((a,i)=>`<button data-answer="${i}">${esc(a)}</button>`).join('')}</div>`;}
  function battle(s){const mine=myIndex(),enemy=1-mine;setTimeout(()=>body.querySelectorAll('[data-shot]').forEach(x=>x.onclick=()=>transact(n=>{if(n.turn!==mine||n.winner!==null)return;const i=+x.dataset.shot;if(n.shots[mine][i]!==undefined)return;const hit=!!n.boards[enemy][i];n.shots[mine][i]=hit?1:0;if(hit)n.hits[mine]++;if(n.hits[mine]>=17)n.winner=mine;else n.turn=enemy;return n;})),0);const ownShots=s.shots[enemy],their=s.shots[mine];return `<div class="battle-wrap"><section><h4>${esc(t().ships)} · ${17-s.hits[enemy]}</h4><div class="battle-board">${s.boards[mine].map((ship,i)=>`<i class="${ship?'ship':''} ${ownShots[i]===1?'hit':ownShots[i]===0?'miss':''}"></i>`).join('')}</div></section><section><h4>${esc(t().battle)}</h4><div class="battle-board target">${s.boards[enemy].map((_,i)=>`<button data-shot="${i}" class="${their[i]===1?'hit':their[i]===0?'miss':''}"></button>`).join('')}</div></section></div>`;}
  document.addEventListener('DOMContentLoaded',()=>{Object.keys(I18N).forEach(l=>{if(window.TRANSLATIONS?.[l])Object.assign(window.TRANSLATIONS[l],I18N[l]);});document.getElementById('games-btn')?.addEventListener('click',openHub);});
})();
